[package]
name = "chatroom"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-channel = "0.3.31"
futures-util = "0.3.31"
serde = "1.0.219"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
tokio-tungstenite = "0.27.0"
